### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by benregn** [ozeetee/jqtimeline#3]
The demo site http://goto.io/jqtimeline/ is not working right now

**Comment by fedmich** [comment]
@ozeetee  bump, hope you get notified.
It is not working and only shows a blank white page using puppet

**Comment by benstr** [comment]
Yo, this has been down for a LONNNNNGNGGGNGNGNGNGNGNGNG time. Whats up @ozeetee ?

**Comment by ozeetee** [comment]
Hey benstr wats up. Busy with nodejs and reatjs these days. Will make it up again.

**Comment by abaldwin99** [comment]
Here's a demo I found on google...

http://www.jqueryscript.net/demo/Lightweight-jQuery-Timeline-Plugin-jqtimeline/
